### ISSUE TITLE
Make rebuild command compatible with CircleCI 2.0

### ISSUE THREAD

**Issue by simonplend** [Financial-Times/n-heroku-tools#514]
The rebuild command currently only supports CircleCI 2.0.

**TODO**

- [x] Update the command to use v2 of the `next-service-registry` (`/v2/services.json`)
- [x] Check which version of the CircleCI platform a project is running on
- [x] Trigger CircleCI 2.0 project build via [new API endpoint](https://gist.github.com/ndintenfass/a5a0a8b559057f29a63218e545033d3a#file-build-triggering-via-api-md), but don't try and remove build cache as you can't do that on CircleCI 2.0
- [ ] Enable `builds-service` feature flag in `app` CircleCI preset in Vault

**Comment by sjparkinson** [comment]
> The following endpoint requires that you turn on the new build processing setting for your project (under the Advanced section of your project's Settings page).

Can probably do this for everything by updating the app configuration in Vault to set this feature to on. Inspect the network tab when making the change manually to find out the name of the feature.

Shout if you want a had with this bit.

**Comment by simonplend** [comment]
Have enabled `builds-service` feature flag for all of our CircleCI presets in Vault.
